version: '2'
services:
  rabitmq:
    image: rabbitmq
    ports:
      - 5000
  mongo:
    image: mongo
    ports:
       - 27017
  tickets:
     build: ./tickets
     depends_on :
       - mongo
     ports:
        - 3001
     environment:
        - MONGO_URL=mongodb://mongo:27017
     command: npm start
  random:
     build: ./random
  registry:
     build: ./registry
  feed:
     build: ./feed
